### ISSUE TITLE
1 Stunde zu spaet

### ISSUE THREAD

**Issue by marcneumannhh** [ahilwers/iobroker_alexa_sunrise#1]
Hi !

Vielleicht kann mir ja einer helfen mit dem Script. Finde den Fehler nicht.
Wenn ich einen Wecker bei meiner Alexa programmiere auf 20:00 Uhr dann wird dieser zu 21 Uhr abgerufen und dem HUE Light so mitgeteilt. Praktisch also ist das Problem, dass alles um eine Stunde verschoben ist, also zu spät das Wake-Up Light angeht, was echt schade ist, da ich super gerne mein altes manuelles Wake Up light von Philips einmotten würde.

Versteh nicht, warum wenn es in IO broker korrekt angezeigt wird er auf die ausgelesene Uhrzeit für das Wakeup Licht eine Stunde rauf haut.
Im IObroker zeigt er das alles korrekt an.

**Comment by ahilwers** [comment]
Hallo!

Das ist komisch. Bei mir funktioniert es problemlos und sieht so im Log aus:

```
javascript.0	sript.js.Haus.Automatisierung.Sonnenaufgang: Current time is Tue Aug 27 2019 18:45:00 GMT+0200 (CEST)
javascript.0	2019-08-27 18:45:00.036	info	script.js.Haus.Automatisierung.Sonnenaufgang: Sunrise starts at Wed Aug 28 2019 04:30:00 GMT+0200 (CEST)
javascript.0	2019-08-27 18:45:00.036	info	script.js.Haus.Automatisierung.Sonnenaufgang: Alarm will be triggered at Wed Aug 28 2019 05:00:00 GMT+0200 (CEST)
javascript.0	2019-08-27 18:45:00.036	info	script.js.Haus.Automatisierung.Sonnenaufgang: 0: Wed Aug 28 2019 05:00:00 GMT+0200 (CEST)
javascript.0	2019-08-27 18:45:00.036	info	script.js.Haus.Automatisierung.Sonnenaufgang: Adding alarm at Wed Aug 28 2019 05:00:00 GMT+0200 (CEST)

```
Passt evtl. etwas auf dem iobroker-Server mit der Zeitzone nicht? Das würde evtl. die Stunde Unterschied erklären. Stimmt die "current time" im Log?

**Comment by marcneumannhh** [comment]
Sorry lag wirklich nur an einer fehlerhaften Instanz im IOBroker.
Aber ein anderes Problem gibt es. Wenn man einen Wecker Montag bis Freitags programmiert dann läuft dieser in die Endlos-Schleife.

**Comment by ahilwers** [comment]
Das mit der Endlosschleife sollte mit dem letzten Commit von mir behoben sein. Ansonsten bitte einen neuen Issue anlegen.

**Comment by marcneumannhh** [comment]
Ich teste. Du bist echt super. Wir genießen es jeden Morgen so schön sanft geweckt zu werden. Danke dir nochmals !!!!!
